/*
  C-file generated by Bin2C
  Compiled:    Jun  2 2020 at 15:49:03

  Copyright (C) 2018
  Segger Microcontroller GmbH
  www.segger.com

  The Embedded Experts
*/

unsigned char _acelfstringtable[15UL + 1] = {
  0x00, 0x2E, 0x73, 0x74, 0x72, 0x74, 0x61, 0x62, 0x00, 0x2E, 0x74, 0x65, 0x78, 0x74, 0x00, 0x00
};

/*************************** End of file ****************************/
